### ISSUE TITLE
librosa version issues : 'Size mismatch between n_fft and window size'

### ISSUE THREAD

**Issue by j-pong** [Kyubyong/tacotron#4] opened 2017-05-26 14:27 UTC
If librosa version < 0.5, error can be reported, it is just version problem.

with 0.4.3 version, even though 'hann' window is set as default, the function raises error.

Just update librosa to last version(current version is 0.5), or make it clear correcting hop_length = hp.hop_length and delete window="hann"

def invert_spectrogram(spectrogram):
    return librosa.istft(spectrogram.T, **hp.hop_length**, win_length=hp.win_length, **window="hann"**)

def invert_spectrogram(spectrogram):
    return librosa.istft(spectrogram.T, **hop_length**=hp.hop_length, win_length=hp.win_length)

**Comment by basuam** [comment] 2017-05-26 18:20
@j-pong 
If the issue is solved can you close it?
Thank you for your help.

**Closed** 2017-05-29 09:04 UTC
